### ISSUE TITLE
Display of recent OSM Notes 

### ISSUE THREAD

**Issue by krishnanammala** [mapbox/osm-comments-frontend#64]
I came across this issue, when I wanted to check my OSM note which I added recently on [24-Aug-2016](http://www.openstreetmap.org/note/685806#map=10/52.4907/13.6034) and when I query for that it was not being shown up. Instead it was showing other notes which were added on March,2016 but not mine which is more recent.

Query link: https://www.mapbox.com/osm-comments/#/notes/?q=bbox:13.12,52.35,13.79,52.65%20from:2015-08-01
- bbox coordinates taken from [here](http://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=13.127236,52.357036,13.78644,52.646219&tab=1&proj=EPSG:4326&places=2) . In this case it was Berlin, where my OSM notes falls within this bbox.

It would be great if it resolves which will help us in collecting stats for our next mapping task in Germany, where we are giving OSM notes for the missing turn restrictions.

cc @geohacker @batpad

**Comment by geohacker** [comment]
Thanks for the ticket @krishnanammala!
Can you help us see if any recent notes show up at all? 

Meanwhile, I'll dig and see what could be wrong.

**Comment by batpad** [comment]
I got this.

**Comment by batpad** [comment]
This is always a bit tricky to debug because `notes` lands only one a day.

Right now kicking off a parse manually on the cmd line:

`/usr/local/src/service-worker/node_modules/osm-comments-notes-parser$ node index.js notes --filename /tmp/planet-notes-latest.osn`

**Comment by geohacker** [comment]
Picking this back up.

**Comment by geohacker** [comment]
The new notes seem to have picked up by the watchbot and processed:
`
[Fri, 02 Sep 2016 18:35:03 GMT] [info] [13d116d3-adfc-49ac-81cf-be247bb3a584] [watchbot] Message: {"Records":[{"eventVersion":"2.0","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2016-09-02T18:34:14.445Z","eventName":"ObjectCreated:Put","userIdentity":{"principalId":"AWS:AROAIZ26ILUMGEU2LGNLM:i-f8bdff7e"},"requestParameters":{"sourceIPAddress":"52.23.214.38"},"responseElements":{"x-amz-request-id":"97B9BEF631765105","x-amz-id-2":"JIFGIko7SjO87vJ7OmWp8kxqI5oHMhW4KffpvXDkv/K4csdwupLyOFBQYSPUHg+CJxSBjKAH20k="},"s3":{"s3SchemaVersion":"1.0","configurationId":"NDRlYTZiYTgtN2I4YS00N2MyLTk1ZWYtMWY5NWZiMzc1M2Qz","bucket":{"name":"osm-changesets","ownerIdentity":{"principalId":"A1SDWPRQ8BOK96"},"arn":"arn:aws:s3:::osm-changesets"},"object":{"key":"notes/2016/planet-notes-160826.osn.bz2","size":46965035,"eTag":"5a4020151663d2dbe46275833bbe0249","sequencer":"0057C9C624EEC9B7DC"}}}]}
[Fri, 02 Sep 2016 18:35:04 GMT] [info] [13d116d3-adfc-49ac-81cf-be247bb3a584] done processing, deleting tmp file
`

**Comment by geohacker** [comment]
I downloaded `planet-notes-160826.osn` to check if @krishnanammala note is in the dump, it is:
`<note id="685806" lat="52.5012361" lon="13.6419752" created_at="2016-08-24T08:53:44Z">`

But it isn't in the osm-comments database. Next I'll start poking the osm-comments-notes-parser.

**Comment by geohacker** [comment]
I ran into this just now. Still looking.

```
node index.js notes --filename /tmp/planet-notes-160826.osn

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'comments' of null
    at SaxStream2.<anonymous> (/usr/local/src/service-worker/node_modules/osm-comments-notes-parser/notes/index.js:49:24)
    at runNextHook (/usr/local/src/service-worker/node_modules/osm-comments-notes-parser/node_modules/sax-async/node_modules/crisphooks/crisphooks.js:129:18)
    at SaxStream2.CrispHooks.trigger (/usr/local/src/service-worker/node_modules/osm-comments-notes-parser/node_modules/sax-async/node_modules/crisphooks/crisphooks.js:152:2)
    at async.(anonymous function).self._eventQueue (/usr/local/src/service-worker/node_modules/osm-comments-notes-parser/node_modules/sax-async/sax-js-async.js:48:17)
    at /usr/local/src/service-worker/node_modules/osm-comments-notes-parser/node_modules/sax-async/node_modules/async/lib/async.js:141:26
    at Object.async.stackSafe (/usr/local/src/service-worker/node_modules/osm-comments-notes-parser/node_modules/sax-async/node_modules/async/lib/async.js:132:13)
    at /usr/local/src/service-worker/node_modules/osm-comments-notes-parser/node_modules/sax-async/node_modules/async/lib/async.js:140:19
    at iterate (/usr/local/src/service-worker/node_modules/osm-comments-notes-parser/node_modules/sax-async/node_modules/async/lib/async.js:177:13)
    at /usr/local/src/service-worker/node_modules/osm-comments-notes-parser/node_modules/sax-async/node_modules/async/lib/async.js:188:25
    at /usr/local/src/service-worker/node_modules/osm-comments-notes-parser/node_modules/sax-async/sax-js-async.js:52:6
```

**Comment by geohacker** [comment]
Trying to see if I can replicate ^ locally.

**Comment by geohacker** [comment]
Okay can reproduce locally along with some logs:

```
### tagName note
currentNote {"name":"NOTE","attributes":{"ID":"580663","LAT":"44.8553889","LON":"10.3062357","CREATED_AT":"2016-06-02T13:22:46Z"},"isSelfClosing":false,"comments":[]}
### tagName comment
# comment node {"name":"COMMENT","attributes":{"ACTION":"opened","TIMESTAMP":"2016-06-02T13:22:46Z","UID":"2748195","USER":"karitotp"},"isSelfClosing":false}
### tagName comment
# comment node {"name":"COMMENT","attributes":{"ACTION":"closed","TIMESTAMP":"2016-06-02T15:15:39Z","UID":"4052720","USER":"Señorita Francisca"},"isSelfClosing":false}

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'comments' of null
    at SaxStream2.<anonymous> (/Users/geohacker/mapbox/osm-comments-parser/notes/index.js:52:24)
```

**Comment by geohacker** [comment]
This happened on a different note:

```
### opentag note
currentNote {"name":"NOTE","attributes":{"ID":"584255","LAT":"41.0141521","LON":"44.4775738","CREATED_AT":"2016-06-05T15:27:53Z","CLOSED_AT":"2016-06-05T19:00:08Z"},"isSelfClosing":false,"comments":[]}
### opentag comment
# comment node {"name":"COMMENT","attributes":{"ACTION":"opened","TIMESTAMP":"2016-06-05T15:27:53Z","UID":"248521","USER":"DrDimedrol"},"isSelfClosing":false}
# closetag COMMENT
# currentNote { name: 'NOTE',
  attributes:
   { ID: '584255',
     LAT: '41.0141521',
     LON: '44.4775738',
     CREATED_AT: '2016-06-05T15:27:53Z',
     CLOSED_AT: '2016-06-05T19:00:08Z' },
  isSelfClosing: false,
  comments:
   [ { name: 'COMMENT',
       attributes: [Object],
       isSelfClosing: false,
       text: '6' } ] }
### opentag comment
# comment node {"name":"COMMENT","attributes":{"ACTION":"closed","TIMESTAMP":"2016-06-05T19:00:08Z","UID":"248521","USER":"DrDimedrol"},"isSelfClosing":true}
# closetag COMMENT
# currentNote { name: 'NOTE',
  attributes:
   { ID: '584255',
     LAT: '41.0141521',
     LON: '44.4775738',
     CREATED_AT: '2016-06-05T15:27:53Z',
     CLOSED_AT: '2016-06-05T19:00:08Z' },
  isSelfClosing: false,
  comments:
   [ { name: 'COMMENT',
       attributes: [Object],
       isSelfClosing: false,
       text: '6' },
     { name: 'COMMENT', attributes: [Object], isSelfClosing: true } ] }
# closetag NOTE
# currentNote { name: 'NOTE',
  attributes:
   { ID: '584255',
     LAT: '41.0141521',
     LON: '44.4775738',
     CREATED_AT: '2016-06-05T15:27:53Z',
     CLOSED_AT: '2016-06-05T19:00:08Z' },
  isSelfClosing: false,
  comments:
   [ { name: 'COMMENT',
       attributes: [Object],
       isSelfClosing: false,
       text: '6' },
     { name: 'COMMENT', attributes: [Object], isSelfClosing: true } ] }
# closetag COMMENT
# currentNote null
### opentag comment
# comment node {"name":"COMMENT","attributes":{"ACTION":"closed","TIMESTAMP":"2016-06-05T22:13:15Z","UID":"1679","USER":"andrewpmk"},"isSelfClosing":true}

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'comments' of null
```

Looks like a race condition?

**Comment by geohacker** [comment]
```
# closetag COMMENT
# currentNote null
### opentag comment
# comment node {"name":"COMMENT","attributes":{"ACTION":"closed","TIMESTAMP":"2016-06-05T22:13:15Z","UID":"1679","USER":"andrewpmk"},"isSelfClosing":true}
# closetag COMMENT
# currentNote null
# closetag NOTE
# currentNote null

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'attributes' of null
    at Object.saveNote (/Users/geohacker/mapbox/osm-comments-parser/notes/db.js:17:23)
```

Definitely looks like the xml isn't being parsed the right way. This random comment shows up midway which isn't attached to the previous note or in the same order as the xml.

**Comment by geohacker** [comment]
Rolled out fixes for this, and reimported all notes. 
@krishnanammala - thanks for catching this. 

🙇

**Comment by geohacker** [comment]
Here's the relevant PR https://github.com/mapbox/osm-comments-parser/pull/19

**Comment by krishnanammala** [comment]
@geohacker Thanks so much for this 🙏  . It will be really useful for our Germany Task 🎉

**Comment by krishnanammala** [comment]
I have checked for the recent [OSM notes](https://www.openstreetmap.org/note/702381) which was added on 6-Sept-2016 in Munich, Germany. And noticed that it was again not being shown up in the [osm-comments-api](https://www.mapbox.com/osm-comments/#/notes/).

It broke again and not showing the recent ones 😢 .

My query: https://www.mapbox.com/osm-comments/#/notes/?q=bbox:11.38,48.05,11.76,48.24%20from:2015-09-01
Munich bbox: http://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=11.389619,48.051505,11.751717,48.23816&tab=1&proj=EPSG:4326&places=2

cc @geohacker @batpad
